name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CONFIGURE_PRESET: "default-release"

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        version: [ v03.02.03814, v3.3.3996, v3.4.4271-stable, dev ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Update submodule
      run: |
        cd vendor/api
        git fetch --tags
        git checkout --force ${{matrix.version}}
    - name: Patch api to allow building headlessly
      run: |
        cd vendor/api
        git apply --verbose ../binja-ci-headless.patch
    - name: Configure CMake
      run: cmake --preset ${{env.CONFIGURE_PRESET}} -G Ninja
    - name: Build
      working-directory: ${{github.workspace}}/out/build
      run: cmake --build ${{env.CONFIGURE_PRESET}}
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.os}}-${{matrix.version}}
        path: ${{github.workspace}}/out/build/${{env.CONFIGURE_PRESET}}/*DePac*